imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

doctrine:
    dbal:
        driver: 'pdo_sqlite'
        memory: true
        charset: UTF8
