imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        cookie_domain: session.storage.mock_file
        handler_id: null
    profiler:
        collect: false

doctrine:
    dbal:
        driver: 'pdo_sqlite'
        memory: true
        charset: UTF8
#    orm:
#        entity_managers:
#            default:
#                report_fields_where_declared: true
